### Messages
GET https://rest.trade-server.net/{{merchantId}}/messages/?channel={{channelId}}
Accept: application/xml
Authorization: basic {{username}} {{password}}

### Stock
GET https://rest.trade-server.net/{{merchantId}}/stock/?channel={{channelId}}
Accept: application/xml
Authorization: basic {{username}} {{password}}

### Catalogue retrieve
GET https://rest.trade-server.net/{{merchantId}}/products/?channel={{channelId}}
Accept: application/xml
Authorization: basic {{username}} {{password}}

### Catalogue sync
POST https://rest.trade-server.net/{{merchantId}}/sync/in/?channel={{channelId}}
Content-Type: application/xml

//@todo put working example here
<?xml version="1.0" encoding="UTF-8"?>
<TBSTOCK></TBSTOCK>

### Orders unprocessed
GET http://rest.trade-server.net/{{merchantId}}/orders/?channel={{channelId}}
Accept: application/xml
Authorization: basic {{username}} {{password}}


### Orders Invoice
GET https://rest.trade-server.net/{{merchantId}}/orders/{{orderId}}/invoice/?channel={{channelId}}
Accept: application/xml
Authorization: basic {{username}} {{password}}